version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    env_file:
      - .env
    command: ./start_django.sh
    volumes:
      - ./src:/code/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "7474:6379"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
  portainer:
    image: portainer/portainer-ce  
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
  nginx:
    build: ./services/nginx/
    ports:
      - "443:443"
    depends_on:
      - web


volumes:
  postgres_data:
    driver: local
  portainer_data:
    driver: local