# Generated by Django 5.0.3 on 2024-04-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_party_partyroom_player_delete_ponggame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='PartyRoom',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
