# Generated by Django 5.0.4 on 2024-04-21 03:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='openent',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent_elo',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent_score',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user_elo',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user_score',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='win',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='date_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='game_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PlayerMatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('elo_change', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.matchhistory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='players',
            field=models.ManyToManyField(through='users.PlayerMatchHistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
