# Generated by Django 5.0.1 on 2024-02-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_blockeduser_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
