# Generated by Django 5.0.3 on 2024-04-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.FloatField(default=1000),
        ),
    ]
