# Generated by Django 5.0.1 on 2024-01-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_friendship_unique_together_blockeduser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='PrivateMessage',
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
