# Generated by Django 5.0.1 on 2024-01-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_chatmessage_privatemessage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
