# Generated by Django 5.0.1 on 2024-01-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together=set(),
        ),
    ]
