# Generated by Django 5.0.4 on 2024-04-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_elo'),
        ('users', '0010_remove_user_oauth_oauthcred_user_oauth_cred'),
    ]

    operations = [
    ]
