# Generated by Django 5.0.1 on 2024-02-13 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1024, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
